### ISSUE TITLE
Priorité des commandes Android->python

### ISSUE THREAD

**Issue by ClementAubry** [ISENRobotics/R2D2-in-the-sky#10]
Existe-t'il un "Panic Button" sur l'application Android, un boutton qui permettrait d'arrêter l'envoi de commande des joystick au profit d'une commande STOP?

**Comment by Noctisae** [comment]
Il existe un bouton d'arrêt d'urgence qui fait rentrer le robot dans un mode spécial, qui déclenche l'arrêt des moteurs et enclenche l'arrêt du fonctionnement du traitement interne du robot pendant 5 secondes pour le moment. De plus, quand aucune commande n'est recue par le robot, celui-ci arrête de bouger automatiquement.
